site_name: Azure FinOps MCP Server
site_url: https://julianobarbosa.github.io/azure-finops-mcp-server/
site_description: Enterprise-grade Azure FinOps capabilities for AI assistants
site_author: Juliano Barbosa

repo_name: julianobarbosa/azure-finops-mcp-server
repo_url: https://github.com/julianobarbosa/azure-finops-mcp-server
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    logo: material/cloud-check
    repo: fontawesome/brands/github
  language: en

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_if_no_docstring: false
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/julianobarbosa
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/azure-finops-mcp-server/
  version:
    provider: mike
  analytics:
    provider: google
    property: "${GOOGLE_ANALYTICS_KEY:-}"

nav:
  - Home: index.md
  - What's New: changelog.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: quickstart.md
  - Architecture:
    - Overview: architecture.md
    - Validation Report: architecture/validation-report.md
  - API Reference:
    - MCP Tools: api/tools.md
  - Deployment: deployment.md
  - License: license.md
  - GitHub: https://github.com/julianobarbosa/azure-finops-mcp-server
